version: "3.8"
# Para servidor Linux
services:
  nginx:
    build:
      context: ./
      args:
        NGINX_VERSION: '1.25.2'
        # https://hub.docker.com/_/nginx
    image: yourusernamedockerhub/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./react-app/build:/usr/share/nginx/html  # Volume atualizado
    networks:
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: on-failure

  react-app:
    build:
      context: ./react-app  # Certifique-se de que este caminho está correto
      dockerfile: Dockerfile
    image: yourusernamedockerhub/react-app
    environment:
      - NODE_ENV=production
    volumes:
      - ./react-app/build:/usr/share/nginx/html
    networks:
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 50M
      restart_policy:
        condition: on-failure

  api:
    build:
      context: ./py-api
      dockerfile: Dockerfile
    image: yourusernamedockerhub/sf-api
    environment:
      - FLASK_ENV=production  # ou outro ambiente adequado
      - MONGO_INITDB_ROOT_USERNAME=your_username
      - MONGO_INITDB_ROOT_PASSWORD=mypass
      - MONGO_URI=mongodb://your_username:mypass@mongodb:27017/your_database
    networks:
      - net_swarm
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 50M
      restart_policy:
        condition: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: mypass
    volumes:
      - mongo_data:/data/db
    networks:
      - net_swarm

networks:
  net_swarm:
    external: true
    name: net_swarm

volumes:
  mongo_data:
